name: Check for push
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  repository_dispatch:
    #types: [my-event(triggered by repoA),my-event(triggered by repoC)]
    #types: [my-event(triggered by ${{ github.repository }}]
      


jobs:

#   myEvent:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.client_payload.ref }}
#       - run: echo ${{ github.event.client_payload.sha }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: script
        run: |
             echo "Hey this is 2nd workflow  "
             echo "Add build steps"
             
